Add support for configurable plot width/height
jenkinsci/plot-plugin pull request #71
Opened 2022-04-26 20:32 UTC by markus-franke

Jira: [JENKINS-59237](https://issues.jenkins.io/browse/JENKINS-59237)

### What has been done
1.
2.

### Screenshots

Before | After
:-: | :-:
| |

### How to test
1.
2.

### Checklist

- [ ] Git commits follow [best practices](https://chris.beams.io/posts/git-commit/) 
- [ ] Build passes in Jenkins 
- [ ] Appropriate tests or explanation to why this change has no tests 
- [ ] Pull Request is marked with appropriate label (see `.github/release-drafter.yml`) 
- [ ] JIRA issue is well described (problem explanation, steps to reproduce, screenshots) 
- [ ] For dependency updates: links to external changelogs and, if possible, full diffs

2023-02-13 06:48 UTC, moo-the-cow commented
I have exactly the same issue. width, height argument does not affect the plot (it should according to documentation).
having like 20 labels on the plot, you cannot properly see anything at default width/height. the whole purpose of the plugin is to visualize data. I'd love to get this prioritized.
Thank you

2024-03-22 04:48 UTC, nvkhoi112358 commented
I would love to see this in the next version.

For now, the only way to enlarge the plot is modify the querystring `getPlot?index=0&width=750&height=450`, not configurable through groovy script.

2025-01-05 14:12 UTC, MarkEWaite commented
@markus-franke sorry for the long delay reviewing the pull request.  

I tested the pull request with Jenkins 2.462.3 and was unable to have it actually apply the values for width and height.  I created a [freestyle project](https://github.com/MarkEWaite/docker-lfs/blob/da86cddd2843906f443e974149d7666675f65fa1/ref/jobs/Bugs-Individual/jobs/Bugs-70-000-to-79-999/jobs/JENKINS-75090-plot-plugin-ui-issues/config.xml), defined the plot height and width, and ran the job several times.  The plot width and height were unchanged on the display.  The plot width and height were not retained in the freestyle job definition form.  When I configured the job again, the width and height fields were empty.

2025-01-05 14:26 UTC, MarkEWaite requested changes
Needs more work to assure that the plot width and height configuration is saved when the form is saved and that the plot width and plot height are used when generating the plot.

2025-01-21 21:36 UTC, markus-franke commented
@MarkEWaite Thanks for getting back to this ;-)

Honestly after 3 years I don't know how to continue working on this. It's long time ago that I was working with Jenkins and I don't even quite remember how to get the plugin up and running again.

Feel free to close the MR. Otherwise maybe somebody else wants to continue working on it.

2025-01-21 22:04 UTC, MarkEWaite commented
> Feel free to close the MR. Otherwise maybe somebody else wants to continue working on it.

Thanks so much @markus-franke .  Closing the pull request.  Others can reopen it if they want to take it further.

2025-01-21 22:04 UTC, closed without merging